spring.application.name=LaClave

#DB
spring.datasource.url=jdbc:oracle:thin:@itwillbs.com:1602:ORCL2412
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=c##team3
spring.datasource.password=oracle3

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#JPA -Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect