spring.application.name=LaClave

#DB
spring.datasource.url=jdbc:oracle:thin:@itwillbs.com:1602:ORCL2412
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=c##team3
spring.datasource.password=oracle3

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#JPA -Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

#이메일 인증
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gkdbs0309@gmail.com
spring.mail.password=gruc gwgh bykv xdrd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.properties.hibernate.default_batch_fetch_size=100
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#ai 연결
gpt.api-url = https://api.openai.com/v1/chat/completions
gpt.api-model = gpt-4o-mini
gpt.api-temperature = 0.5
